def generate_code(prompt, generated_code):
    """
    Formats the generated code into a usable application structure.

    Args:
        prompt (str): The prompt provided by the user.
        generated_code (str): The code generated by the DeepSeek model.

    Returns:
        str: A formatted application structure.
    """
    # If the generated code appears to contain HTML, extract it for better display
    if "html_form" in generated_code or "<style>" in generated_code:
        # Preserve the original code as is to maintain HTML formatting
        return generated_code
    else:
        app_structure = f"""
# Application generated from prompt: {prompt}

import streamlit as st

def main():
    st.title("Generated Application")
    st.write("This application was generated based on the following prompt:")
    st.write("Prompt: {prompt}")
    
    # Generated code begins here
    {generated_code}

if __name__ == "__main__":
    main()
"""
        return app_structure.strip()
