def generate_code(prompt, generated_code):
    """
    Formats the generated code into a usable application structure.

    Args:
        prompt (str): The prompt provided by the user.
        generated_code (str): The code generated by the DeepSeek model.

    Returns:
        str: A formatted application structure.
    """
    app_structure = f"""
# Application generated from prompt: {prompt}

import streamlit as st

def main():
    st.title("Generated Application")
    st.write("This application was generated based on the following prompt:")
    st.write("Prompt: {prompt}")
    
    # Generated code begins here
    {generated_code}

if __name__ == "__main__":
    main()
"""
    return app_structure.strip()
